const express_ts = {
  pkgJson: {
    dependencies: [
      'command-line-args',
      'compression',
      'cookie-parser',
      'cors',
      'dotenv',
      'express',
      'http-status-codes',
      'module-alias',
      'morgan',
      'ramda',
      'reflect-metadata',
      'winston',
    ],
    devDependencies: [
      '@types/command-line-args',
      '@types/compression',
      '@types/cookie-parser',
      '@types/express',
      '@types/find',
      '@types/jest',
      '@types/jsonfile',
      '@types/morgan',
      '@types/node',
      '@types/ramda',
      '@types/supertest',
      '@typescript-eslint/eslint-plugin',
      '@typescript-eslint/parser',
      'cross-env',
      'eslint',
      'eslint-config-prettier',
      'eslint-plugin-prettier',
      'find',
      'fs-extra',
      'husky',
      'jest',
      'jsonfile',
      'nodemon',
      'prettier',
      'supertest',
      'ts-jest',
      'ts-node',
      'tsconfig-paths',
      'typescript',
    ],
  },
}
const express_es6 = {
  pkgJson: {
    dependencies: [
      'command-line-args',
      'compression',
      'cookie-parser',
      'cors',
      'dotenv',
      'express',
      'http-status-codes',
      'module-alias',
      'morgan',
      'ramda',
      'winston',
    ],
    devDependencies: [
      'cross-env',
      'eslint',
      'eslint-config-prettier',
      'eslint-plugin-import',
      'eslint-plugin-prettier',
      'find',
      'fs-extra',
      'husky',
      'jest',
      'jsonfile',
      'nodemon',
      'prettier',
      'supertest',
    ],
  },
}

module.exports = {
  express_es6,
  express_ts,
}
